<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="hand">


  <xacro:macro name="hand" params="connected_to:='' ns:='' rpy:='0 0 0' xyz:='0 0 0' ">
    <xacro:unless value="${connected_to == ''}">
      <joint name="${ns}_hand_joint" type="fixed">
        <parent link="${connected_to}"/>
        <child link="${ns}_hand"/>
        <origin xyz="${xyz}" rpy="${rpy}"/>
      </joint>
    </xacro:unless>
    
    <link name="${ns}_hand">
      <visual>
        <geometry>
          <mesh filename="package://franka_panda_description/meshes/visual/hand.dae"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://franka_panda_description/meshes/collision/hand.stl"/>
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="0 0.0015244 0.0275912"/>
        <mass value="0.73"/>
        <inertia ixx="0.00278560230025" ixy="0.0" ixz="0.0" iyy="0.000400033405336" iyz="0.0" izz="0.00256378041832"/>
      </inertial>
    </link>
    
    <link name="${ns}_leftfinger">
      <visual>
        <geometry>
          <mesh filename="package://franka_panda_description/meshes/visual/finger.dae"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://franka_panda_description/meshes/collision/finger.stl"/>
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="0 0.0145644 0.0227941"/>
        <mass value="0.1"/>
        <inertia ixx="3.01220925051e-05" ixy="0.0" ixz="0.0" iyy="2.95873808038e-05" iyz="0.0" izz="6.95125211657e-06"/>
      </inertial>
    </link>
    <link name="${ns}_rightfinger">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <geometry>
          <mesh filename="package://franka_panda_description/meshes/visual/finger.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <geometry>
          <mesh filename="package://franka_panda_description/meshes/collision/finger.stl"/>
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 3.141592653589793" xyz="0 -0.0145644 0.0227941"/>
        <mass value="0.1"/>
        <inertia ixx="3.01220925051e-05" ixy="0.0" ixz="0.0" iyy="2.95873808038e-05" iyz="0.0" izz="6.95125211657e-06"/>
      </inertial>

    </link>
    <joint name="${ns}_finger_joint1" type="prismatic">
      <parent link="${ns}_hand"/>
      <child link="${ns}_leftfinger"/>
      <origin xyz="0 0.0095 0.0584" rpy="0 0 0"/> <!-- 0.0095-->
      <axis xyz="0 1 0"/>
      <limit effort="20" lower="0.0" upper="0.04" velocity="0.2"/>
      <dynamics damping="500.0" friction="0.0"/>
    </joint>
    <joint name="${ns}_finger_joint2" type="prismatic">
      <parent link="${ns}_hand"/>
      <child link="${ns}_rightfinger"/>
      <origin xyz="0 -0.0095 0.0584" rpy="0 0 0"/> <!-- 0.0095-->
      <axis xyz="0 -1 0"/>
      <limit effort="20" lower="0.0" upper="0.04" velocity="0.2"/>
      <dynamics damping="500.0" friction="0.0"/>
      <mimic joint="${ns}_finger_joint1" />
    </joint>

    <xacro:property name="_distance1" value="0.0584"/>
    <xacro:property name="_distance2" value="0.03626585"/><!-- 0.09466585*-->

    <link name="${ns}_peg">    
      <visual>
        <geometry>
          <mesh filename="package://franka_panda_description/meshes/collision/peg.STL"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
           <mesh filename="package://franka_panda_description/meshes/collision/peg.STL"/>
        </geometry>
      </collision>

      <inertial>
        <origin rpy="0 0 0" xyz="0 0 0.01504"/>
        <mass value="0.02264"/>
        <inertia ixx="2.6576e-6" ixy="0.0" ixz="0.0" iyy="8.2317e-7" iyz="0.0" izz="3.6303e-6"/>
      </inertial>
    </link>
<!--

    <joint name="${ns}_pegjoint" type="revolute">
      <parent link="${ns}_hand"/>
      <child link="${ns}_peg"/>
      <origin xyz="0 0 ${_distance1 + _distance2}" rpy="0 0 3.14"/>
      <axis xyz="0 0 1"/>
      <limit velocity="6.5" effort="1000" lower="0" upper="0" />
    </joint>
-->

    <joint name="${ns}_pegjoint" type="fixed">
<!--
      <preserveFixedJoint>true</preserveFixedJoint>
-->
      <parent link="${ns}_hand"/>
      <child link="${ns}_peg"/>
      <origin xyz="0 0 ${_distance1 + _distance2 + 0.035}" rpy="0 3.14159265358979 0"/>
<!--
      <sensor name="${ns}_pegjoint_force_torque" type="force_torque">
        <always_on>true</always_on>
        <visualize>false</visualize>
        <force_torque>
          <frame>child</frame>
          <measure_direction>child_to_parent</measure_direction>
        </force_torque>
        <updateRate>30.0</updateRate>
        <topicName>/gazebo/robot/peg/ft</topicName>
      </sensor>
-->
    </joint>

<!--
    <gazebo reference="${ns}_pegjoint">
      <sensor name="${ns}_pegjoint_force_torque" type="force_torque">
        <always_on>true</always_on>
        <visualize>true</visualize>
        <force_torque>
          <frame>sensor</frame>
          <measure_direction>child_to_parent</measure_direction>
        </force_torque>
      </sensor>
    </gazebo>
    
    <gazebo>
      <plugin name="ft_sensor" filename="libgazebo_ros_ft_sensor.so">
        <updateRate>30.0</updateRate>
        <topicName>/gazebo/robot/peg/ft</topicName>
        <jointName>panda_pegjoint</jointName>
      </plugin>
    </gazebo>

    <gazebo reference="${ns}_peg">
      <selfCollide>true</selfCollide>
    </gazebo>

    <gazebo reference="${ns}_peg">
      <sensor name='${ns}_peg_contact' type='contact'>
        <update_rate> 50 </update_rate>
        <always_on>true</always_on>
          <contact>
              <collision>${ns}_peg_collision</collision>
          </contact>
          <plugin name="peg_bumper" filename="libgazebo_ros_bumper.so">
            <bumperTopicName>${ns}_peg_collision</bumperTopicName>
            <frameName>${ns}_peg</frameName>
          </plugin>
      </sensor>
    </gazebo>
-->
    

  



  </xacro:macro>
</robot>
